version: '3.1'
 
services:
 
  main:
    image: kevinkoolwhip/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass
  mongo:
    image: mongo
    ports:
      - 27017:27017
  app:
    image: kevinkoolwhip/nodeapp
    ports:
      - 8081:8081
    links:
      - mongo
 
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
